/**
 * SourceDataSection - Seccion de datos de la fuente + campo idInstrumento
 *
 * Muestra:
 * - Datos de la fuente (nombreFuente, fuente, moneda):
 *   - Si viene de cola (queueItemId !== null): Campos readonly
 *   - Si es nuevo instrumento sin cola (queueItemId === null): Campos editables
 * - Checkbox "Instrumento Nuevo" - Para crear nuevo instrumento con ID auto-generado
 * - Campo idInstrumento:
 *   - Si esInstrumentoNuevo: Campo bloqueado con ID auto-generado
 *   - Si NO esInstrumentoNuevo: TextField simple (la búsqueda se hace desde el FAB SearchHelper)
 */

import { useState, useCallback, useMemo } from 'react';
import {
  Chip,
  Box,
  Alert,
  FormControlLabel,
  Checkbox,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Button,
  alpha,
} from '@mui/material';
import SourceOutlinedIcon from '@mui/icons-material/SourceOutlined';
import AddCircleOutlineIcon from '@mui/icons-material/AddCircleOutline';
import { FormSection, FormRow } from '../layout';
import { ReadOnlyField, TextField, SelectField } from '../fields';
import { colors } from '../../styles/theme';

// Estilos para el campo ID auto-generado (usando tokens del tema)
const autoGeneratedStyles = {
  '& .MuiOutlinedInput-root': {
    backgroundColor: alpha(colors.secondary.main, 0.08),
    '& fieldset': { borderColor: colors.secondary.light, borderWidth: 2 },
    '&:hover fieldset': { borderColor: colors.secondary.main },
    '&.Mui-focused fieldset': { borderColor: colors.secondary.light },
  },
};

const SourceDataSection = ({
  formData,
  handleChange,
  isFieldReadOnly,
  modeLabel,
  modeColor,
  modeDescription,
  registroEncontrado,
  // Nuevos props para instrumento nuevo
  activarInstrumentoNuevo,
  desactivarInstrumentoNuevo,
  // Props para modo sin cola (Nuevo Instrumento tab)
  queueItemId = null,
  options = {},
}) => {
  // Determinar si los campos de fuente son editables (cuando no viene de cola)
  const isSourceEditable = queueItemId === null;
  // Estado para el dialogo de confirmacion
  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);

  // Manejar cambio del checkbox "Instrumento Nuevo"
  const handleInstrumentoNuevoChange = useCallback(async (e) => {
    const { checked } = e.target;

    if (checked) {
      // Activar modo instrumento nuevo
      if (activarInstrumentoNuevo) {
        await activarInstrumentoNuevo();
      }
    } else {
      // Mostrar dialogo de confirmacion antes de desactivar
      setConfirmDialogOpen(true);
    }
  }, [activarInstrumentoNuevo]);

  // Confirmar desactivacion de instrumento nuevo
  const handleConfirmDesactivar = useCallback(() => {
    setConfirmDialogOpen(false);
    if (desactivarInstrumentoNuevo) {
      desactivarInstrumentoNuevo();
    }
  }, [desactivarInstrumentoNuevo]);

  // Cancelar desactivacion
  const handleCancelDesactivar = useCallback(() => {
    setConfirmDialogOpen(false);
  }, []);

  // Determinar si el checkbox debe estar deshabilitado
  const isCheckboxDisabled = useMemo(() => {
    // Deshabilitado si es reestructuracion (reestructuracion fuerza instrumento nuevo)
    return formData.esReestructuracion || isFieldReadOnly('esInstrumentoNuevo');
  }, [formData.esReestructuracion, isFieldReadOnly]);

  return (
    <FormSection
      title="Datos de la Fuente"
      icon={<SourceOutlinedIcon color="primary" />}
      action={
        modeLabel && (
          <Chip
            label={modeLabel}
            color={modeColor}
            size="small"
            sx={{ fontWeight: 600 }}
          />
        )
      }
    >
      {/* Primera fila: Datos de la fuente */}
      <FormRow>
        {isSourceEditable ? (
          /* MODO NUEVO INSTRUMENTO (sin cola): Campos editables */
          <>
            <TextField
              name="nombreFuente"
              label="Nombre en Fuente"
              value={formData.nombreFuente || ''}
              onChange={handleChange}
              width="flex2"
              required
              placeholder="Ingrese el nombre del instrumento en la fuente"
            />
            <SelectField
              name="fuente"
              label="Fuente"
              value={formData.fuente || ''}
              onChange={handleChange}
              options={options?.fuentes || []}
              width="md"
              required
            />
            <SelectField
              name="moneda"
              label="Moneda Fuente"
              value={formData.moneda || ''}
              onChange={handleChange}
              options={options?.monedas || []}
              width="md"
              required
            />
          </>
        ) : (
          /* MODO COLA DE PENDIENTES: Campos readonly */
          <>
            <ReadOnlyField
              name="nombreFuente"
              label="Nombre en Fuente"
              value={formData.nombreFuente}
              width="flex2"
            />
            <ReadOnlyField
              name="fuente"
              label="Fuente"
              value={formData.fuente}
              width="sm"
            />
            <ReadOnlyField
              name="moneda"
              label="Moneda Fuente"
              value={formData.moneda}
              width="sm"
            />
            <ReadOnlyField
              name="subId"
              label="SubID"
              value={formData.subId}
              width="sm"
            />
          </>
        )}
      </FormRow>

      {/* Checkbox Instrumento Nuevo */}
      <FormRow>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <FormControlLabel
            control={
              <Checkbox
                checked={formData.esInstrumentoNuevo || false}
                onChange={handleInstrumentoNuevoChange}
                disabled={isCheckboxDisabled}
                sx={{
                  color: colors.secondary.main,
                  '&.Mui-checked': { color: colors.secondary.main },
                }}
              />
            }
            label={
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                <AddCircleOutlineIcon
                  fontSize="small"
                  sx={{ color: formData.esInstrumentoNuevo ? colors.secondary.main : 'inherit' }}
                />
                <span style={{
                  fontWeight: formData.esInstrumentoNuevo ? 600 : 400,
                  color: formData.esInstrumentoNuevo ? colors.secondary.main : 'inherit',
                }}>
                  Instrumento Nuevo (ID auto-generado)
                </span>
              </Box>
            }
          />
          {formData.esReestructuracion && (
            <Chip
              label="Reestructuración activa"
              size="small"
              color="secondary"
              variant="outlined"
            />
          )}
        </Box>
      </FormRow>

      {/* Campo ID_Instrumento - siempre readonly
          El ID solo se establece de 2 formas:
          1. Auto-generado cuando "Instrumento Nuevo" está marcado
          2. Desde SearchHelper al seleccionar Exacta/Parcial
      */}
      <FormRow>
        <ReadOnlyField
          name="idInstrumento"
          label={formData.esInstrumentoNuevo ? "ID_Instrumento (auto-generado)" : "ID_Instrumento"}
          value={formData.idInstrumento || ''}
          width="md"
          helperText={
            formData.esInstrumentoNuevo
              ? "ID generado automáticamente"
              : formData.idInstrumento
                ? "Seleccionado desde búsqueda"
                : "Use ★ Buscar en Stock para seleccionar"
          }
          sx={formData.esInstrumentoNuevo ? autoGeneratedStyles : undefined}
        />
      </FormRow>

      {/* Mensaje de estado del modo */}
      {modeDescription && (
        <Box sx={{ mt: 2 }}>
          <Alert
            severity={
              modeColor === 'success' ? 'success' :
              modeColor === 'warning' ? 'warning' :
              modeColor === 'info' ? 'info' : 'info'
            }
            sx={{ py: 0.5 }}
          >
            {modeDescription}
            {registroEncontrado && (
              <Box component="span" sx={{ fontWeight: 600, ml: 1 }}>
                (ID: {registroEncontrado.idInstrumento}, Moneda: {registroEncontrado.moneda})
              </Box>
            )}
          </Alert>
        </Box>
      )}

      {/* Dialogo de confirmacion para desactivar instrumento nuevo */}
      <Dialog
        open={confirmDialogOpen}
        onClose={handleCancelDesactivar}
        aria-labelledby="confirm-dialog-title"
        aria-describedby="confirm-dialog-description"
      >
        <DialogTitle id="confirm-dialog-title">
          ¿Desmarcar Instrumento Nuevo?
        </DialogTitle>
        <DialogContent>
          <DialogContentText id="confirm-dialog-description">
            Se perderán <strong>todos los datos ingresados</strong> en el formulario.
            ¿Está seguro de que desea continuar?
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCancelDesactivar} color="primary">
            Cancelar
          </Button>
          <Button onClick={handleConfirmDesactivar} color="error" variant="contained">
            Sí, desmarcar
          </Button>
        </DialogActions>
      </Dialog>
    </FormSection>
  );
};

export default SourceDataSection;
